name: build-and-deploy
on:
  push:
    branches: [ master ]

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
jobs:
  build-and-deploy:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: install dependencies
        run: yarn
      - name: builds site
        run: yarn build

      - name: deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: master
          # github-token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
        